apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ include "otusapp-chart.fullname" . }}
  labels:
    {{- include "otusapp-chart.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
        - path: /otusapp/ksalov(/|$)(.*)
          backend:
            serviceName: {{ include "otusapp-chart.fullname" . }}
            servicePort: {{ .Values.service.port }}
